### ISSUE TITLE
failed to get data when generating YAML

### ISSUE THREAD

**Issue by jneb802** [RustyMods/Almanac#1]
First off, thank you for amazing mod. I was thinking this would be especially useful for newer players like me. 

When I opened the trophy tab for the first time after installing mod, I had a few seconds of lag. I checked the logs and saw this error. 

[BeeQueen](https://valheim.thunderstore.io/package/OdinPlus/BeeQueen/) is from this mod
[rae_OdinHorse](https://valheim.thunderstore.io/package/OdinPlus/OdinHorse/) is from this mod
[Hare](https://valheim.thunderstore.io/package/blacks7ar/OdinsHares/1.0.1/) is from this mod (I assume)

> [Message:   Almanac] Almanac Creature Data YAML file missing, generating...
> [Warning:   Almanac] failed to get humanoid data of BeeQueen, continuing...
> [Warning:   Almanac] failed to get character data of BeeQueen, continuing...
> [Warning:   Almanac] failed to get humanoid data of rae_Offspring_Normal, continuing...
> [Warning:   Almanac] failed to get character data of rae_Offspring_Normal, continuing...
> [Warning:   Almanac] failed to get humanoid data of rae_OdinHorse, continuing...
> [Warning:   Almanac] failed to get character data of rae_OdinHorse, continuing...
> [Warning:   Almanac] failed to get humanoid data of Hare, continuing...
> [Warning:   Almanac] failed to get character data of Hare, continuing...
> [Info   : Unity Log] Creature data collected and saved YAML file to C:\Users\jneb8\AppData\Roaming\r2modmanPlus-local\Valheim\profiles\Valheim1\BepInEx\config\AlmanacCreatureData.yml

**Comment by RustyMods** [comment]
Thank you for the feedback. These messages are there by design to help the user know why some of the information may not be available. Also, the lag is there during the generation of the YAML file which is a serialized file in order to avoid lag every time the user opens the Almanac.

By saving the data to this file, now the Almanac can pull data from this file instead of having to go through the process for each trophy. If you ever install any new mods that add more creatures, you can simply "regenerate almanac" in order add the new creatures to the file for usage.

Hare is from the original game but is a special case as it is uniquely missing most of the creature components. That warning will always appear as my code attempts to get all the data for creatures.

Currently working on tabs that will enable access to see creature data for the creatures that do not have trophies as well as compatibility with other mods that add creatures, such as Odin horse and Cretaceous to name a few.

If you see any "red" messages in your logs is when you should be worried.

Best,
Rusty
